services:
  staging:
    image: ghcr.io/navneetr7/hewhocodes-website:staging
    container_name: hewhocodes-staging
    env_file:
      - .env.staging
    restart: unless-stopped
    ports:
      - "127.0.0.1:3001:3000"
    volumes:
      - /var/run/postgresql:/var/run/postgresql:ro
      - /var/lib/hewhocodes/blog-media/staging:/app/blog-media
    profiles:
      - staging

  production:
    image: ghcr.io/navneetr7/hewhocodes-website:production
    container_name: hewhocodes-production
    env_file:
      - .env.production
    restart: unless-stopped
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - /var/run/postgresql:/var/run/postgresql:ro
      - /var/lib/hewhocodes/blog-media/production:/app/blog-media
    profiles:
      - production
